# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180709_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
