version: '3.6'
services:
  db:
    image: mariadb:10.0.35
    volumes:
      - ../dkdata/marida_10.0.35:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=djavue-twitter
      - MYSQL_USER=djavue-twitter
      - MYSQL_PASSWORD=djavue-twitter
    ports:
      - "33061:3306"
  web:
    image: djavue-twitter
    container_name: djavue-twitter
    build: .
    command: start_dev.sh
    environment:
      - DJANGO_DB_HOST=db
    depends_on:
      - db
    ports:
      - '8000:8000'
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ../..:/app
  nginx:
    image: nginx
    network_mode: "host"
    volumes:
      - ../nginx/default_local:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
